wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.13
    start_time: 1660703996.912251
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.8.13
      5: 0.13.1
      8:
      - 2
      - 5
